Details page
Project-MKB/project-mkb pull request #40
Opened 2019-11-11 05:16 UTC by kststudio

fixes #22

2019-11-12 21:56 UTC, sdymj84 requested changes
![image](https://user-images.githubusercontent.com/8356367/68713355-4114ba00-0563-11ea-81fa-baf93bf43f00.png)

Since DetailsHero and MainHero are pretty identical except for title and content, I would create one 'Hero.js' file under the global folder and invoke it from main and detail page as below.

Hero.js
![image](https://user-images.githubusercontent.com/8356367/68713563-c39d7980-0563-11ea-81a2-b5e4ce0c60d4.png)

main.js
![image](https://user-images.githubusercontent.com/8356367/68713724-1e36d580-0564-11ea-9ec7-021b2878fad5.png)

details.js
![image](https://user-images.githubusercontent.com/8356367/68714243-1fb4cd80-0565-11ea-9703-f5ada9187079.png)


so that we make Hero.js reusable component and use it anywhere it needs to be. I would say this is the whole point of why we use component-based frameworks

2019-11-12 21:56 UTC, sdymj84 commented on frontend/src/components/details/Gallery.js
> +import React, { Component } from 'react';
Component is unused

2019-11-14 05:30 UTC, kststudio commented on frontend/src/components/details/Gallery.js
> +import React, { Component } from 'react';
this is all set

2019-11-14 16:27 UTC, sdymj84 approved these changes
RecipeInstructions.js has warning with 'class'
I'll merge and fix on my PR
Thank you!

2019-11-14 16:27 UTC, sdymj84 commented on frontend/src/components/details/RecipeInstructions.js
> +        <div class="container">
error from 'class'
I'll merge and fix it from my PR

2019-11-14 16:27 UTC, merged