Update recipe - fixes #31
Project-MKB/project-mkb pull request #44
Opened 2019-11-14 21:09 UTC by sdymj84

2019-11-21 04:50 UTC, kststudio approved these changes

2019-11-21 04:53 UTC, kststudio requested changes
There is a conflict on the following files:
frontend/src/App.js
frontend/src/redux/actions/recipeActions.js
frontend/src/redux/reducers/recipeReducer.js

2019-11-21 20:56 UTC, sdymj84 commented
Fixed the merge conflict. Can you review again?

2019-11-29 22:43 UTC, kststudio approved these changes

2019-11-29 22:44 UTC, merged